# Bash Configuration
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }

# GoLang Configuration
[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path=stdout", "--show-stats=false", "--issues-exit-code=1"]

[language-server.gopls.config]
gofumpt = true
hints = { assignVariableTypes = true, compositeLiteralFields = true, compositeLiteralTypes = true, constantValues = true, functionTypeParameters = true, rangeVariableTypes = true }

[[language]]
name = "go"
formatter = { command = "goimports" }

# JSON Configuration
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }

# Ruby Configuration
[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true, inlayHint = true }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]
