# Bash Configuration
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }

[language-server.gopls.config]
gofumpt = true
hints = { assignVariableTypes = true, compositeLiteralFields = true, compositeLiteralTypes = true, constantValues = true, functionTypeParameters = true, rangeVariableTypes = true }

[[language]]
name = "go"
formatter = { command = "goimports" }

# JSON Configuration
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }

# Ruby Configuration
[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true, inlayHint = true }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]

# TOML Configuration
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

# Frontend Configuration
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "svelte"
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-svelte",
  "--parser",
  "svelte",
] }
language-servers = [
  "svelteserver",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
]

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]
