# Bash Configuration
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }

# GoLang Configuration
[language-server.gopls.config]
gofumpt = true

[[language]]
name = "go"
formatter = { command = "goimports" }

# JSON Configuration
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }

# Ruby Configuration
[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true, inlayHint = true }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp"]
