# Grammar Setup
[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls]
userDictPath = "~/.config/harper/dictionary.txt"
fileDictPath = "./.harper/file-dictionaries"
diagnosticSeverity = "warning"
isolateEnglish = true
dialect = "British"

[language-server.harper-ls.config.harper-ls.linters]
BoringWords = true
ToDoHyphen = false

# Bash Configuration
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }

# C and C++ Configuration
[[language]]
name = "c"
file-types = ["c", "h"]
formatter = { command = 'clang-format' }

[[language]]
name = "cpp"
file-types = ["cpp", "cc", "cxx", "hpp", "hcc", "hxx"]
formatter = { command = 'clang-format' }

# Go Configuration
[language-server.gopls.config]
gofumpt = true

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
rangeVariableTypes = true

[[language]]
name = "go"
formatter = { command = "goimports" }
language-servers = ["gopls", "golangci-lint-lsp", "harper-ls"]

# JSON Configuration
[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
language-servers = ["vscode-json-language-server", "harper-ls"]

[[language]]
name = "jsonc"
formatter = { command = 'prettier', args = ["--parser", "jsonc"] }
language-servers = ["vscode-json-language-server", "harper-ls"]

# Ruby Configuration
[language-server.ruby-lsp]
command = "ruby-lsp"
config = { diagnostics = true, formatting = true, inlayHint = true }

[[language]]
name = "ruby"
language-servers = ["ruby-lsp", "harper-ls"]

# TOML Configuration
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
language-servers = ["taplo", "harper-ls"]

# Frontend Configuration
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "harper-ls",
]

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
language-servers = ["markdown-oxide", "harper-ls"]

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "harper-ls",
]

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "harper-ls",
]

[[language]]
name = "svelte"
formatter = { command = "prettier", args = [
  "--plugin",
  "prettier-plugin-svelte",
  "--parser",
  "svelte",
] }
language-servers = [
  "svelteserver",
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  "harper-ls",
]

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "harper-ls",
]

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "harper-ls",
]
